### PR TITLE
Update http-server dependency

### PR DESCRIPTION
**Pull request by sharwell**
Fixes a failure to load samples. See http-party/http-server#525.

### CODE REVIEW

**Comment by alexdima** [comment]
We've moved away from `http-server` because it wasn't working well on Windows.

**Comment by thornjad** [comment]
@alexdima what doesn't work well on windows? I'm trying to make sure http-server has all issues accounted for

**Comment by alexdima** [comment]
I think it was https://github.com/http-party/http-server/issues/525 that we were running into.

**Comment by thornjad** [comment]
👍 That's what I figured, just wanted to be sure there wasn't anything else

**Pull request closed without merging**
